spring:
  #  profiles:
  #    active: dev
  #
  datasource:
    # initialization-mode: always
#   ↓自宅デスクトップ用
#    url: jdbc:mysql://aasfjipizluevw.cvdtfnwyixqf.ap-northeast-1.rds.amazonaws.com:3306/ebdb
    url: jdbc:mysql://localhost:3306/db_name
#    url: jdbc:mysql://ecshop2.cvdtfnwyixqf.ap-northeast-1.rds.amazonaws.com:3306/db_name
    username: root
#    username: admin
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: true
  session:
    jdbc:
      initialize-schema: always
  mvc:
    view:
      prefix: /templates/
      suffix: .html
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.domain.model
server:
  port: 5000

  application: properties
#spring:
#    servlet:
#        multipart: max-request-size=10MB
#        multipart: multipart.max-file-size=10MB

#  cloud.aws:
#      credentials:
#        accessKey: AKIARTKN2SQVKISVPFFL
#         secretKey: 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
#      region:
#          auto: false
#         static: ap-northeast-1