spring:
  #  profiles:
  #    active: dev
  datasource:
    # initialization-mode: always
    url: jdbc:mysql://aasfjipizluevw.cvdtfnwyixqf.ap-northeast-1.rds.amazonaws.com:3306/ebdb
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: true
  session:
    jdbc:
      initialize-schema: always
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.domain.model
server:
  port: 5000
