# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B install --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run:  mvn -B package --file pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: AKIARTKN2SQVOER2Q3R3
        aws_secret_key: p12hE4OUckuhajHKzwQokouTgu7U4hfxv5Bb53I7
        application_name: Samplel
        environment_name: Samplel-env
        version_label: ${{ github.run_number }}
        region: ap-northeast-1
        deployment_package: target/demo-0.0.1-SNAPSHOT.jar
    
